// Mock plot listings data for Reznicocare
export const mockProperties = [
    {
        id: 'vrunda-city',
        title: 'Vrunda City – Hoskote, Bagalur',
        description:
            'A premium gated plotted development by ASR Developers spread across 17.16 acres in the rapidly growing Hoskote–Bagalur corridor of Bengaluru. Offering 296 thoughtfully planned residential plots with 60-feet wide internal roads, a grand entrance, high-rise overhead water tank, underground drainage, and a modern Sewage Treatment Plant. Designed for a secure, luxurious lifestyle with 30+ world-class amenities including a clubhouse, gym, swimming pool, and badminton courts. Bank loan facility available. Prices start from ₹32.99 Lakhs.',
        price: 3299000, // ₹32.99 Lakhs (1000 sq.ft entry price)
        address: 'Hoskote – Chintamani Road, Bagalur, Hoskote',
        city: 'Hoskote',
        state: 'Karnataka',
        zipCode: '562114',
        country: 'India',
        latitude: 13.1127,
        longitude: 77.8097,
        propertyType: 'RESIDENTIAL_PLOT',
        plotType: 'Residential Plot',
        status: 'AVAILABLE',
        bedrooms: 0,
        bathrooms: 0,
        sqft: 1500, // 1500 sq.ft (mid-range plot)
        sqYards: 167,
        dimensions: '30×50',
        lotSize: 1500,
        yearBuilt: null,
        features: [
            'RERA Approved',
            'Clear Title',
            'Gated Community',
            'Bank Loan Available',
            '60-ft Wide Internal Roads',
            'Underground Drainage (UGD)',
        ],
        amenities: [
            'Clubhouse',
            'Swimming Pool',
            'Fully Equipped Gym',
            'Badminton Courts',
            'Spa & Wellness',
            'Party Lawn & Hall',
            "Children's Play Area",
            'Walking & Jogging Track',
            'Gardens & Landscaping',
            '24/7 Security',
            '24-Hour Power Backup',
            'Overhead Water Tank',
            'Indoor Games Area',
            'Visitor Parking',
            'Street Lighting',
        ],
        featured: true,
        virtualTourUrl: 'https://realtydoor.com/real-estate/vrunda-city/',
        views: 487,
        createdAt: new Date('2024-02-10'),
        updatedAt: new Date('2024-02-10'),
        userId: 'agent1',
        images: [
            {
                id: 'vrunda-img1',
                url: 'https://realtydoor.com/wp-content/uploads/2025/12/banner-3-scaled.webp',
                alt: 'Vrunda City – Entrance View',
                caption: 'Grand entrance to Vrunda City, Hoskote',
                order: 0,
                propertyId: 'vrunda-city',
                createdAt: new Date(),
            },
            {
                id: 'vrunda-img2',
                url: 'https://realtydoor.com/wp-content/uploads/2025/12/banner-1-scaled.webp',
                alt: 'Vrunda City – Layout Plan',
                caption: '17.16-acre master-planned layout with 296 plots',
                order: 1,
                propertyId: 'vrunda-city',
                createdAt: new Date(),
            },
            {
                id: 'vrunda-img3',
                url: 'https://realtydoor.com/wp-content/uploads/2025/12/banner-1-1-copy-scaled.webp',
                alt: 'Vrunda City – Internal Roads',
                caption: '60-feet wide black-top internal roads',
                order: 2,
                propertyId: 'vrunda-city',
                createdAt: new Date(),
            },
            {
                id: 'vrunda-img4',
                url: 'https://realtydoor.com/wp-content/uploads/2025/12/master-plan-scaled.webp',
                alt: 'Vrunda City – Master Plan',
                caption: 'Master plan of 17.16-acre gated community',
                order: 3,
                propertyId: 'vrunda-city',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Vani — Realtydoor',
            email: 'info@realtydoor.com',
            phone: '+91-98450-12345',
            image: null,
        },
    },
    {
        id: 'neo-serene',
        title: 'Neo Serene – Near Hoskote, Bangalore',
        description:
            "Serene is designed to deliver on all of the important bits – convenience, comfort, space, and wellbeing. It promises an effortlessly connected lifestyle through the wealth of amenities and established infrastructure. Welcome to Neo Serene. Come, capitalize on Hoskote's immense potential and secure a stake in its bright future. Fully developed plots, ready for registration.",
        price: 2400000, // Starting price
        address: 'Near Hoskote, Hoskote–Bagalur Corridor',
        city: 'Hoskote',
        state: 'Karnataka',
        zipCode: '562114',
        country: 'India',
        latitude: 13.1205,
        longitude: 77.8356,
        propertyType: 'RESIDENTIAL_PLOT',
        plotType: 'Residential Plot',
        status: 'AVAILABLE',
        bedrooms: 0,
        bathrooms: 0,
        sqft: 1350,
        sqYards: 150,
        dimensions: '30×45',
        lotSize: 1500,
        yearBuilt: null,
        features: [
            'Clear Title',
            'Affordable Luxury',
            'Fully Developed Infrastructure',
            'Tranquil Living',
            'Practical Layout',
            'Strategic Location',
        ],
        amenities: [
            'Clubhouse',
            'Jogging Track & Footpaths',
            "Children's Play Area",
            'Yoga and Meditation Area',
            'Park with Landscape Garden',
            'Avenue Plantation',
            '24/7 Security',
            'CCTV Surveillance',
            'Underground Drainage with STP',
            '24/7 Water Supply',
            'Underground Electrification',
            'Compound Wall',
        ],
        featured: true,
        virtualTourUrl: 'https://realtydoor.com/real-estate/neoserene/',
        views: 312,
        createdAt: new Date('2024-02-12'),
        updatedAt: new Date('2024-02-12'),
        userId: 'agent1',
        images: [
            {
                id: 'neo-serene-img1',
                url: 'https://realtydoor.com/wp-content/uploads/2025/09/banner-1-1-scaled.png',
                alt: 'Neo Serene – Entrance View',
                caption: 'Neo Serene gated community, Near Hoskote',
                order: 0,
                propertyId: 'neo-serene',
                createdAt: new Date(),
            },
            {
                id: 'neo-serene-img2',
                url: 'https://realtydoor.com/wp-content/uploads/2025/09/banner-1-2-scaled.png',
                alt: 'Neo Serene – Community View',
                caption: '11-acre planned layout with 154 plots',
                order: 1,
                propertyId: 'neo-serene',
                createdAt: new Date(),
            },
            {
                id: 'neo-serene-img3',
                url: 'https://realtydoor.com/wp-content/uploads/2025/09/Untitled-design-71.png',
                alt: 'Neo Serene – Master Plan',
                caption: 'Master plan of Neo Serene gated community',
                order: 2,
                propertyId: 'neo-serene',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Vani — Realtydoor',
            email: 'info@realtydoor.com',
            phone: '+91-98450-12345',
            image: null,
        },
    },
    {
        id: 'aashrithaa-brindavan',
        title: 'Aashrithaa Brindavan – Kanakapura Road, Near Art of Living',
        description:
            "Live your dream lifestyle in a lush sanctuary situated next to Art of Living International Center, off Kanakapura Road – South Bengaluru's Best Address. At Aashrithaa Brindavan, you'll discover more than just well-crafted residential plots — you'll be embraced by nature's serene beauty in an idyllic haven designed to keep you connected to all that you love in life.",
        price: 2200000,
        address: 'Kanakapura Road, Near Art of Living International Center',
        city: 'Bangalore',
        state: 'Karnataka',
        zipCode: '562106',
        country: 'India',
        latitude: 12.7966,
        longitude: 77.5151,
        propertyType: 'RESIDENTIAL_PLOT',
        plotType: 'Residential Plot',
        status: 'AVAILABLE',
        bedrooms: 0,
        bathrooms: 0,
        sqft: 1500,
        sqYards: 167,
        dimensions: '30×50',
        lotSize: 2155,
        yearBuilt: null,
        features: ['Clear Title', 'Affordable Luxury', 'Tranquil Living', 'Practical Layout', 'Strategic Location', 'Fully Developed Infrastructure'],
        amenities: ['Parks', 'Jogging Track', "Children's Play Area", 'Entrance Gate', '24/7 Security', 'CCTV Surveillance', 'CC Roads', 'STP Tank', '24/7 Water Supply', 'Underground Electrical & Water Lines'],
        featured: true,
        virtualTourUrl: 'https://realtydoor.com/real-estate/neoserene/',
        views: 402,
        createdAt: new Date('2024-05-01'),
        updatedAt: new Date('2024-05-01'),
        userId: 'agent1',
        images: [
            {
                id: 'brindavan-img1',
                url: 'https://realtydoor.com/wp-content/uploads/2024/05/aashrithaa-brindhavan1-1.jpg',
                alt: 'Aashrithaa Brindavan – Main View',
                caption: 'Lush sanctuary near Art of Living, Kanakapura Road',
                order: 0,
                propertyId: 'aashrithaa-brindavan',
                createdAt: new Date(),
            },
            {
                id: 'brindavan-img2',
                url: 'https://realtydoor.com/wp-content/uploads/2024/05/aashrithaa-brindhavan-2.jpg',
                alt: 'Aashrithaa Brindavan – Community',
                caption: '14-acre plotted development with 236 plots',
                order: 1,
                propertyId: 'aashrithaa-brindavan',
                createdAt: new Date(),
            },
            {
                id: 'brindavan-img3',
                url: 'https://realtydoor.com/wp-content/uploads/2024/05/aashrithaa-brindhavan-3.jpg',
                alt: 'Aashrithaa Brindavan – Green Spaces',
                caption: 'Nature-first layout with parks and plantation',
                order: 2,
                propertyId: 'aashrithaa-brindavan',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Vani — Realtydoor',
            email: 'info@realtydoor.com',
            phone: '+91-98450-12345',
            image: null,
        },
    },
    {
        id: 'aashrithaa-divine',
        title: 'Aashrithaa Divine – Jigani, Bengaluru',
        description:
            "Nestled in the heart of Jigani, these exclusive plots by Aashrithaa Properties are set to redefine your idea of the perfect living space. This is where all of life's pleasures are in abundance. At Aashrithaa Divine, you're just a stone's throw away from established schools, your work place and this location is poised for an exciting transformation.",
        price: 2000000,
        address: 'Jigani, Bengaluru',
        city: 'Bangalore',
        state: 'Karnataka',
        zipCode: '560105',
        country: 'India',
        latitude: 12.7541,
        longitude: 77.6459,
        propertyType: 'RESIDENTIAL_PLOT',
        plotType: 'Residential Plot',
        status: 'AVAILABLE',
        bedrooms: 0,
        bathrooms: 0,
        sqft: 1500,
        sqYards: 167,
        dimensions: '30×50',
        lotSize: 2155,
        yearBuilt: null,
        features: ['Fully Developed Infrastructure', 'Serene Living', 'Superb Connectivity', 'Ready to Build', 'Ready for Registration', 'Best Investment Opportunity'],
        amenities: ['Parks with Landscaped Gardens', "Children's Playground", 'Jogging Tracks', 'Avenue Plantation', 'Round the Clock Security', 'Compound Wall', 'Asphalted Roads', 'Underground Drainage', 'Street Lights'],
        featured: true,
        virtualTourUrl: 'https://youtu.be/yag8beq3qZU',
        views: 318,
        createdAt: new Date('2024-05-01'),
        updatedAt: new Date('2024-05-01'),
        userId: 'agent1',
        images: [
            {
                id: 'divine-img1',
                url: 'https://realtydoor.com/wp-content/uploads/2024/05/devine-1.webp',
                alt: 'Aashrithaa Divine – Main View',
                caption: 'Where happiness begins – Jigani, Bengaluru',
                order: 0,
                propertyId: 'aashrithaa-divine',
                createdAt: new Date(),
            },
            {
                id: 'divine-img2',
                url: 'https://realtydoor.com/wp-content/uploads/2024/05/devine-2.webp',
                alt: 'Aashrithaa Divine – Community View',
                caption: '14-acre plotted development with 236 plots',
                order: 1,
                propertyId: 'aashrithaa-divine',
                createdAt: new Date(),
            },
            {
                id: 'divine-img3',
                url: 'https://realtydoor.com/wp-content/uploads/2024/05/devine-3.webp',
                alt: 'Aashrithaa Divine – Green Spaces',
                caption: 'Wide roads, parks, and serene surroundings',
                order: 2,
                propertyId: 'aashrithaa-divine',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Vani — Realtydoor',
            email: 'info@realtydoor.com',
            phone: '+91-98450-12345',
            image: null,
        },
    },
    {
        id: 'newtownj',
        title: 'NewtownJ – Punganur, Andhra Pradesh',
        description:
            "Experience luxury living with over 30 top-tier amenities in a 60-acre modern era township at Punganur, Andhra Pradesh. The property boasts twin lakes providing serene lakeside hangouts amidst lush greenery. It's more than just a residential space — it's a glimpse into the future of urbanisation. PKM-UDA approved. 750 plots, multiple sizes available.",
        price: 1800000, // ₹18 Lakhs
        address: 'NewtownJ Township, Punganur, Chittoor Dist.',
        city: 'Punganur',
        state: 'Andhra Pradesh',
        zipCode: '517247',
        country: 'India',
        latitude: 13.3688,
        longitude: 78.5662,
        propertyType: 'RESIDENTIAL_PLOT',
        plotType: 'Residential Plot',
        status: 'AVAILABLE',
        bedrooms: 0,
        bathrooms: 0,
        sqft: 1500,
        sqYards: 167,
        dimensions: '30×50',
        lotSize: 1500,
        yearBuilt: null,
        features: [
            'PKM-UDA Approved',
            'Clear Title',
            'Affordable Luxury',
            'Twin Lakes',
            'Smart Amenities',
            'Serene Living',
        ],
        amenities: [
            'Clubhouse',
            "Children's Play Area",
            'Jogging Track',
            'Parks & Landscaped Gardens',
            'CCTV Surveillance',
            '24/7 Security with Compound Wall',
            'Swimming Pool',
            'Yoga & Meditation Zone',
            'Avenue Plantation',
            'Underground Drainage',
        ],
        featured: true,
        virtualTourUrl: 'https://youtu.be/_T1dY6liEcw',
        views: 412,
        createdAt: new Date('2024-05-01'),
        updatedAt: new Date('2024-05-01'),
        userId: 'agent1',
        images: [
            {
                id: 'ntj-img1',
                url: 'https://realtydoor.com/wp-content/uploads/2024/05/j-town-1.webp',
                alt: 'NewtownJ – Main View',
                caption: 'Modern Era Township – Punganur, Andhra Pradesh',
                order: 0,
                propertyId: 'newtownj',
                createdAt: new Date(),
            },
            {
                id: 'ntj-img2',
                url: 'https://realtydoor.com/wp-content/uploads/2024/05/j-town-2.webp',
                alt: 'NewtownJ – Community Spaces',
                caption: '60-acre township with twin lakes',
                order: 1,
                propertyId: 'newtownj',
                createdAt: new Date(),
            },
            {
                id: 'ntj-img3',
                url: 'https://realtydoor.com/wp-content/uploads/2024/05/j-town-3.webp',
                alt: 'NewtownJ – Green Landscape',
                caption: 'Man-made plantations and serene greenery',
                order: 2,
                propertyId: 'newtownj',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Vani — Realtydoor',
            email: 'info@realtydoor.com',
            phone: '+91-98450-12345',
            image: null,
        },
    },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

export function getFeaturedProperties() {
    return mockProperties.filter((p) => p.featured).slice(0, 6);
}

export function getProperties(page: number = 1, limit: number = 12) {
    const start = (page - 1) * limit;
    const end = start + limit;
    return {
        properties: mockProperties.slice(start, end),
        total: mockProperties.length,
        page,
        totalPages: Math.ceil(mockProperties.length / limit),
    };
}

export function getPropertyById(id: string) {
    return mockProperties.find((p) => p.id === id) || null;
}

// Format price in Indian style: ₹ X Lakhs / ₹ X Cr
export function formatIndianPrice(price: number): string {
    if (price >= 10000000) {
        return `₹${(price / 10000000).toFixed(2)} Cr`;
    } else if (price >= 100000) {
        return `₹${(price / 100000).toFixed(0)} Lakhs`;
    }
    return `₹${price.toLocaleString('en-IN')}`;
}
