// Mock data for development without database
export const mockProperties = [
    {
        id: 'serenity-manor',
        title: 'The Serenity Manor Residences',
        description:
            'An exclusive sanctuary where contemporary design meets uncompromising luxury. Nestled in the heart of Bangalore\'s most prestigious neighborhood with premium finishes and smart home technology.',
        price: 42500000,
        address: '#785/10, 2nd Floor, 14th cross',
        city: 'Jayanagar',
        state: 'Karnataka',
        zipCode: '560082',
        country: 'India',
        latitude: 12.9352,
        longitude: 77.5869,
        propertyType: 'APARTMENT',
        status: 'AVAILABLE',
        bedrooms: 3,
        bathrooms: 3.5,
        sqft: 3200,
        lotSize: null,
        yearBuilt: 2024,
        features: [
            'Smart Home',
            'Italian Marble',
            'Panoramic Views',
            'Premium Finishes',
            'Energy Efficient',
        ],
        amenities: ['Swimming Pool', 'Gym', 'Spa', '24/7 Security', 'Clubhouse', 'Smart Home'],
        featured: true,
        virtualTourUrl: '',
        views: 245,
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15'),
        userId: 'agent1',
        images: [
            {
                id: 'img1',
                url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
                alt: 'The Serenity Manor - Exterior',
                caption: 'Stunning exterior view',
                order: 0,
                propertyId: 'serenity-manor',
                createdAt: new Date(),
            },
            {
                id: 'img2',
                url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
                alt: 'Living Room',
                caption: 'Spacious living room',
                order: 1,
                propertyId: 'serenity-manor',
                createdAt: new Date(),
            },
            {
                id: 'img3',
                url: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200&q=80',
                alt: 'Kitchen',
                caption: 'Modern kitchen',
                order: 2,
                propertyId: 'serenity-manor',
                createdAt: new Date(),
            },
            {
                id: 'img4',
                url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&q=80',
                alt: 'Bedroom',
                caption: 'Master bedroom',
                order: 3,
                propertyId: 'serenity-manor',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Sarah Johnson',
            email: 'agent@realestate.com',
            phone: '+1-555-0101',
            image: null,
        },
    },
    {
        id: 'earth-villa',
        title: 'The Earth Villa',
        description:
            'A magnificent 4-bedroom villa where spacious living meets sophisticated design. Features geothermal cooling, private pool, landscaped gardens, and premium imported finishes throughout.',
        price: 61000000,
        address: 'EPIP Zone, Whitefield',
        city: 'Whitefield',
        state: 'Karnataka',
        zipCode: '560066',
        country: 'India',
        latitude: 12.9698,
        longitude: 77.7499,
        propertyType: 'VILLA',
        status: 'AVAILABLE',
        bedrooms: 4,
        bathrooms: 4.5,
        sqft: 5500,
        lotSize: 8000,
        yearBuilt: 2024,
        features: [
            'Private Pool',
            'Geothermal Cooling',
            'Home Theater',
            'Wine Cellar',
            'Landscaped Garden',
        ],
        amenities: ['Private Pool', 'Smart Home', 'Solar Power', '24/7 Security', 'Staff Quarters'],
        featured: true,
        virtualTourUrl: '',
        views: 189,
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date('2024-01-10'),
        userId: 'agent1',
        images: [
            {
                id: 'img5',
                url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80',
                alt: 'The Earth Villa - Exterior',
                caption: 'Villa exterior',
                order: 0,
                propertyId: 'earth-villa',
                createdAt: new Date(),
            },
            {
                id: 'img6',
                url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
                alt: 'Living Area',
                caption: 'Spacious living area',
                order: 1,
                propertyId: 'earth-villa',
                createdAt: new Date(),
            },
            {
                id: 'img7',
                url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&q=80',
                alt: 'Kitchen',
                caption: 'Gourmet kitchen',
                order: 2,
                propertyId: 'earth-villa',
                createdAt: new Date(),
            },
            {
                id: 'img8',
                url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&q=80',
                alt: 'Bedroom',
                caption: 'Master bedroom',
                order: 3,
                propertyId: 'earth-villa',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Sarah Johnson',
            email: 'agent@realestate.com',
            phone: '+1-555-0101',
            image: null,
        },
    },
    {
        id: 'forest-estate',
        title: 'Forest Estate',
        description:
            'The pinnacle of luxury living. A sprawling 5-bedroom estate with full solar array, private amenities, and unmatched sophistication across 7,800 sq.ft in Bangalore\'s most prestigious address.',
        price: 84500000,
        address: '80 Feet Road, Koramangala',
        city: 'Koramangala',
        state: 'Karnataka',
        zipCode: '560095',
        country: 'India',
        latitude: 12.9352,
        longitude: 77.6245,
        propertyType: 'VILLA',
        status: 'AVAILABLE',
        bedrooms: 5,
        bathrooms: 6.0,
        sqft: 7800,
        lotSize: 12000,
        yearBuilt: 2024,
        features: ['Private Elevator', 'Full Solar Array', 'Rooftop Terrace', 'Library', 'Chef Kitchen'],
        amenities: ['Private Gym', 'Sauna', 'Wine Cellar', '4-Car Garage', 'Smart Home'],
        featured: true,
        virtualTourUrl: '',
        views: 312,
        createdAt: new Date('2024-01-05'),
        updatedAt: new Date('2024-01-05'),
        userId: 'agent1',
        images: [
            {
                id: 'img9',
                url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
                alt: 'Forest Estate - Exterior',
                caption: 'Estate exterior',
                order: 0,
                propertyId: 'forest-estate',
                createdAt: new Date(),
            },
            {
                id: 'img10',
                url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&q=80',
                alt: 'Living Room',
                caption: 'Grand living room',
                order: 1,
                propertyId: 'forest-estate',
                createdAt: new Date(),
            },
            {
                id: 'img11',
                url: 'https://images.unsplash.com/photo-1556912173-3bb406ef7e77?w=1200&q=80',
                alt: 'Kitchen',
                caption: 'Luxury kitchen',
                order: 2,
                propertyId: 'forest-estate',
                createdAt: new Date(),
            },
            {
                id: 'img12',
                url: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=80',
                alt: 'Bedroom',
                caption: 'Master bedroom',
                order: 3,
                propertyId: 'forest-estate',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Sarah Johnson',
            email: 'agent@realestate.com',
            phone: '+1-555-0101',
            image: null,
        },
    },
    {
        id: 'skyline-penthouse',
        title: 'Skyline Penthouse',
        description:
            'A masterpiece of contemporary design suspended above the city. Experience unparalleled luxury with 360-degree skyline views from this exclusive Manhattan penthouse.',
        price: 12500000,
        address: '432 Park Avenue, 45th Floor',
        city: 'Manhattan',
        state: 'NY',
        zipCode: '10022',
        country: 'USA',
        latitude: 40.7614,
        longitude: -73.9776,
        propertyType: 'APARTMENT',
        status: 'AVAILABLE',
        bedrooms: 4,
        bathrooms: 5.0,
        sqft: 6800,
        lotSize: null,
        yearBuilt: 2024,
        features: ['Floor-to-Ceiling Windows', 'Italian Marble', 'Smart Home', 'Private Elevator', 'Rooftop Terrace'],
        amenities: ['Concierge 24/7', 'Private Fitness Center', 'Wine Cellar', 'Spa', 'Secured Parking'],
        featured: true,
        virtualTourUrl: '',
        views: 428,
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date('2024-01-20'),
        userId: 'agent1',
        images: [
            {
                id: 'skyline1',
                url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200',
                alt: 'Skyline Penthouse - Living Room',
                caption: 'Panoramic city views',
                order: 0,
                propertyId: 'skyline-penthouse',
                createdAt: new Date(),
            },
            {
                id: 'skyline2',
                url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200',
                alt: 'Master Bedroom',
                caption: 'Luxurious master suite',
                order: 1,
                propertyId: 'skyline-penthouse',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Sarah Johnson',
            email: 'agent@realestate.com',
            phone: '+1-555-0101',
            image: null,
        },
    },
    {
        id: 'coastal-villa',
        title: 'Coastal Villa',
        description:
            'A breathtaking oceanfront sanctuary where modern architecture meets coastal elegance. Direct beach access and panoramic Pacific views from this Malibu masterpiece.',
        price: 18900000,
        address: '27500 Pacific Coast Highway',
        city: 'Malibu',
        state: 'CA',
        zipCode: '90265',
        country: 'USA',
        latitude: 34.0259,
        longitude: -118.7798,
        propertyType: 'VILLA',
        status: 'AVAILABLE',
        bedrooms: 6,
        bathrooms: 7.0,
        sqft: 9200,
        lotSize: 15000,
        yearBuilt: 2024,
        features: ['Infinity Pool', 'Private Beach', 'Outdoor Kitchen', 'Tennis Court', 'Wine Cellar'],
        amenities: ['Home Theater', 'Fitness Center', 'Spa', 'Boat Dock', 'Smart Home'],
        featured: true,
        virtualTourUrl: '',
        views: 567,
        createdAt: new Date('2024-01-18'),
        updatedAt: new Date('2024-01-18'),
        userId: 'agent1',
        images: [
            {
                id: 'coastal1',
                url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200',
                alt: 'Coastal Villa - Exterior',
                caption: 'Oceanfront paradise',
                order: 0,
                propertyId: 'coastal-villa',
                createdAt: new Date(),
            },
            {
                id: 'coastal2',
                url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200',
                alt: 'Pool Area',
                caption: 'Infinity pool with ocean views',
                order: 1,
                propertyId: 'coastal-villa',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Sarah Johnson',
            email: 'agent@realestate.com',
            phone: '+1-555-0101',
            image: null,
        },
    },
    {
        id: 'urban-loft',
        title: 'Urban Loft',
        description:
            'A stunning conversion of historic industrial space into a contemporary masterpiece. Soaring ceilings, exposed brick, and original architectural details in the heart of SoHo.',
        price: 8200000,
        address: '125 Greene Street',
        city: 'SoHo',
        state: 'NY',
        zipCode: '10012',
        country: 'USA',
        latitude: 40.7247,
        longitude: -74.0028,
        propertyType: 'APARTMENT',
        status: 'AVAILABLE',
        bedrooms: 3,
        bathrooms: 3.5,
        sqft: 4200,
        lotSize: null,
        yearBuilt: 1890,
        features: ['Exposed Brick', 'Timber Beams', 'Cast-Iron Columns', 'Private Terrace', 'Smart Home'],
        amenities: ['24-Hour Doorman', 'Rooftop Terrace', 'Fitness Center', 'Bike Storage', 'Package Room'],
        featured: true,
        virtualTourUrl: '',
        views: 389,
        createdAt: new Date('2024-01-16'),
        updatedAt: new Date('2024-01-16'),
        userId: 'agent1',
        images: [
            {
                id: 'loft1',
                url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200',
                alt: 'Urban Loft - Living Space',
                caption: 'Industrial chic living',
                order: 0,
                propertyId: 'urban-loft',
                createdAt: new Date(),
            },
            {
                id: 'loft2',
                url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200',
                alt: 'Master Suite',
                caption: 'Spacious master bedroom',
                order: 1,
                propertyId: 'urban-loft',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Sarah Johnson',
            email: 'agent@realestate.com',
            phone: '+1-555-0101',
            image: null,
        },
    },
    {
        id: 'mountain-estate',
        title: 'Mountain Estate',
        description:
            'A private mountain sanctuary offering unparalleled luxury amidst breathtaking alpine scenery. 35 acres of pristine wilderness at 9,000 feet elevation in Aspen.',
        price: 24500000,
        address: '1200 Red Mountain Road',
        city: 'Aspen',
        state: 'CO',
        zipCode: '81611',
        country: 'USA',
        latitude: 39.1911,
        longitude: -106.8175,
        propertyType: 'VILLA',
        status: 'AVAILABLE',
        bedrooms: 7,
        bathrooms: 9.0,
        sqft: 12500,
        lotSize: 1524600, // 35 acres in sqft
        yearBuilt: 2024,
        features: ['Ski-In/Ski-Out', 'Heated Pool', 'Wine Cellar', 'Home Theater', 'Helipad'],
        amenities: ['Private Spa', 'Fitness Center', 'Sauna', 'Steam Room', '8-Car Garage'],
        featured: true,
        virtualTourUrl: '',
        views: 612,
        createdAt: new Date('2024-01-14'),
        updatedAt: new Date('2024-01-14'),
        userId: 'agent1',
        images: [
            {
                id: 'mountain1',
                url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200',
                alt: 'Mountain Estate - Exterior',
                caption: 'Alpine majesty',
                order: 0,
                propertyId: 'mountain-estate',
                createdAt: new Date(),
            },
            {
                id: 'mountain2',
                url: 'https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=1200',
                alt: 'Mountain Views',
                caption: 'Panoramic mountain vistas',
                order: 1,
                propertyId: 'mountain-estate',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Sarah Johnson',
            email: 'agent@realestate.com',
            phone: '+1-555-0101',
            image: null,
        },
    },
    {
        id: 'beachfront-mansion',
        title: 'Beachfront Mansion',
        description:
            'An architectural masterpiece on 200 feet of pristine white sand beach. Where the ocean becomes your backyard in this ultra-luxury Miami Beach estate.',
        price: 32000000,
        address: '5800 Collins Avenue',
        city: 'Miami Beach',
        state: 'FL',
        zipCode: '33140',
        country: 'USA',
        latitude: 25.8267,
        longitude: -80.1216,
        propertyType: 'VILLA',
        status: 'AVAILABLE',
        bedrooms: 8,
        bathrooms: 10.0,
        sqft: 15000,
        lotSize: 25000,
        yearBuilt: 2024,
        features: ['Private Beach', 'Infinity Pool', 'Boat Dock', 'Wine Cellar', 'Helipad'],
        amenities: ['Home Theater', 'Tennis Court', 'Spa', 'Outdoor Kitchen', 'Staff Quarters'],
        featured: true,
        virtualTourUrl: '',
        views: 789,
        createdAt: new Date('2024-01-12'),
        updatedAt: new Date('2024-01-12'),
        userId: 'agent1',
        images: [
            {
                id: 'beach1',
                url: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1200',
                alt: 'Beachfront Mansion - Exterior',
                caption: 'Oceanfront paradise',
                order: 0,
                propertyId: 'beachfront-mansion',
                createdAt: new Date(),
            },
            {
                id: 'beach2',
                url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200',
                alt: 'Pool Area',
                caption: 'Infinity pool overlooking ocean',
                order: 1,
                propertyId: 'beachfront-mansion',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Sarah Johnson',
            email: 'agent@realestate.com',
            phone: '+1-555-0101',
            image: null,
        },
    },
    {
        id: '4',
        title: 'Mountain Peak Chalet',
        description:
            'Stunning alpine retreat with ski-in/ski-out access. Features exposed timber beams, stone fireplaces, and panoramic mountain views.',
        price: 5900000,
        address: '789 Alpine Way',
        city: 'Aspen',
        state: 'CO',
        zipCode: '81611',
        country: 'USA',
        latitude: 39.1911,
        longitude: -106.8175,
        propertyType: 'HOUSE',
        status: 'AVAILABLE',
        bedrooms: 5,
        bathrooms: 5.5,
        sqft: 5200,
        lotSize: 8000,
        yearBuilt: 2020,
        features: ['Ski-In/Ski-Out', 'Mountain Views', 'Fireplace', 'Hot Tub', 'Game Room'],
        amenities: ['Heated Driveway', 'Mudroom', 'Boot Warmers', 'Wine Storage', 'Sauna'],
        featured: false,
        virtualTourUrl: '',
        views: 156,
        createdAt: new Date('2024-01-01'),
        updatedAt: new Date('2024-01-01'),
        userId: 'agent1',
        images: [
            {
                id: 'img13',
                url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200',
                alt: 'Mountain Peak Chalet - Exterior',
                caption: 'Mountain view',
                order: 0,
                propertyId: '4',
                createdAt: new Date(),
            },
            {
                id: 'img14',
                url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200',
                alt: 'Living Room',
                caption: 'Cozy living room',
                order: 1,
                propertyId: '4',
                createdAt: new Date(),
            },
            {
                id: 'img15',
                url: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200',
                alt: 'Kitchen',
                caption: 'Mountain kitchen',
                order: 2,
                propertyId: '4',
                createdAt: new Date(),
            },
            {
                id: 'img16',
                url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200',
                alt: 'Bedroom',
                caption: 'Bedroom suite',
                order: 3,
                propertyId: '4',
                createdAt: new Date(),
            },
        ],
        user: {
            id: 'agent1',
            name: 'Sarah Johnson',
            email: 'agent@realestate.com',
            phone: '+1-555-0101',
            image: null,
        },
    },
];

// Helper function to get featured properties
export function getFeaturedProperties() {
    return mockProperties.filter((p) => p.featured).slice(0, 6);
}

// Helper function to get all properties with pagination
export function getProperties(page: number = 1, limit: number = 12) {
    const start = (page - 1) * limit;
    const end = start + limit;
    return {
        properties: mockProperties.slice(start, end),
        total: mockProperties.length,
        page,
        totalPages: Math.ceil(mockProperties.length / limit),
    };
}

// Helper function to get property by ID
export function getPropertyById(id: string) {
    return mockProperties.find((p) => p.id === id) || null;
}
